### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by gus6177** [candrews/grails-jcaptcha-plugin#13]
When I run the plugin locally it works fine.  When I: deploy it to dev/test environments it throws these errors..  Looks like a bug..

Jun 04, 2015 15:50:53
ERROR
org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver
org.apache.commons.logging.impl.SLF4JLog 

SocketException occurred when processing request: [GET] /dbeqt/jcaptcha/wav/sound.smi Broken pipe. Stacktrace follows:java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.grails.plugin.jcaptcha.JcaptchaController.wav(JcaptchaController.groovy:57)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

AND THIS ERROR

Jun 04, 2015 15:50:53 
ERROR 
org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver 
org.apache.commons.logging.impl.SLF4JLog 

IllegalStateException occurred when processing request: [GET] /dbeqt/jcaptcha/wav/sound.smi
getOutputStream() has already been called for this response. Stacktrace follows:org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
    at java.io.FilterWriter.flush(FilterWriter.java:100)
    ... 5 more

**Comment by gus6177** [comment]
It looks like my issue is that I have the image and sound captcha being called on the same page.  Has anyone ever done this or had this issue?

<div id="imageCaptcha">
                            <h4 class="modal-title" id="myModalLabel">Captcha Image
                                Verification</h4>
                                
                            
                            <br> <span class="captcha" style="margin:0px 10px"> 
                            
                            <a  href="javascript:void(0);" id="refreshCaptcha"
                                class="glyphicon glyphicon-refresh gi-2x"
                                title="Refresh Captcha"> </a>
                            </span>     
                            
                                            
                            <jcaptcha:jpeg name="image" />
                            
                            
                            <span class="captcha" style="margin:0px 15px">
                            <a href="javascript:void(0);"
                                onclick="changeCaptchaMode();"
                                class="glyphicon glyphicon-headphones gi-2x"
                                title="Use Sound Captcha"></a></span>
                                
                        </div>
                    

```
                    <div id="soundCaptcha">
                        <div class="text-center">
                            <h4 class="modal-title" id="myModalLabel">Captcha Sound
                                Verification</h4>
                        </div>

                        <div class="text-center">
                            <div class="modal-body">Please press play and enter the
                                Sound Captcha</div>
                        </div>
                        <jcaptcha:wav name="sound" autostart="0" width="0" height="0"
                            id="soundChallenge" />
                        <g:field type="button" name="playAudio" value="Play Audio"
                            onclick="document.getElementById('soundChallenge').Play()" />
                        <span class="captcha"><a href="javascript:void(0);"
                            onclick="changeCaptchaMode();"
                            class="glyphicon glyphicon-text-width gi-2x"
                            title="Use Image Captcha"></a></span>

                    </div>
```
